
build:
  environment:
    python: 3.10
  nodes:
    my-tests:
      dependencies:
        before:
          - "pip install --upgrade poetry"
          - "make"
    analysis:
      project_setup:
        override:
          - "true"
      tests:
        override:
          - py-scrutinizer-run
          - command: pylint-run
            # we can control the exact checks on the website
            # for example, I disabled pylint checks that black contradicts or that I disagreed with
            #use_website_config: true
checks:
  python:
    code_rating: true
    duplicate_code: true
    
filter:
    excluded_paths:
        - tests/*
        - examples/*        