checks:
    python:
        code_rating: true
        duplicate_code: true

build:
  nodes:
    analysis:
      tests:
        override:
          - py-scrutinizer-run
build:
  nodes:
    analysis:
      tests:
        override:
          - py-scrutinizer-run
          - command: pylint-run p2g



   
