name: build,  test, coverage

on:
  push:
    branches:
      - master
# Cancel running jobs for the same workflow and branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: on ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }} 
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build everything, run tests.
        run: |
          make 
      - name: Upload coverage
        uses: codecov/codecov-action@v3

