name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    name: on ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install dependencies and build
      run: |
        make
    - name: Send to pypi
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}    
      run: |
       make publish
        

